### ISSUE TITLE
Kenneth's Big Idea #1 - Peer Review by Sudha

### ISSUE THREAD

**Issue by susub31** [w201rdada/portfolio-susub31#2]
Peer Review by Sudha (on @kckenneth Big Idea #1):

- Gist: Make machine your friend and personalize it for your needs

- A nice introduction (beginning) Ken; sets the stage for the need for the sentient machine.  I would move the information on FAIR to beginning section, so that the middle section can be focused on the how-to part

- I recently came across how robots are used to offer 'nursing' services in hospitals in Japan.  Please find more details at: [Robots-on-Nursing-Duties](http://www.zdnet.com/article/robots-take-on-nursing-duties-at-japanese-hospitals/)

- The end section captures the utility of your idea and how you see the value for it.  Please refer to [Robot-Bears-Preferred](http://foreignpolicy.com/2017/03/01/japan-prefers-robot-bears-to-foreign-nurses/).  The user base could be extended based on the article above, as this has already been proven to bring smiles to patients.

**Comment by kckenneth** [comment]
Thanks very much for your helpful links, Sudha. I have implemented your links in my portfolio. Although I like to polish my portfolio a bit more, I cannot currently do so with a tight schedule in the work. Either good or bad, robots are slowly taking place in some humans jobs for sure in coming years. Unless we're prepared ourselves in some niche, it's most likely we're gonna have a hard time to replace them. 

Thanks again!
